// framework-comparison/participants/sveltekit/src/lib/IncidentDetail.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { subscribeLiveService } from './live-service.js';
	import { claimIncident, requestAnalysis, submitComment } from './service-client.js';
	import type { AnalysisJob, Incident, User } from './contracts.js';

	let { incident, users, sessionUserId, onIncident } = $props<{
		incident?: Incident;
		users: User[];
		sessionUserId: string;
		onIncident(incident: Incident, mode?: 'optimistic' | 'authoritative'): void;
	}>();
	let draft = $state('');
	let conflict = $state('');
	let error = $state('');
	let job = $state<AnalysisJob | null>(null);
	let busy = $state(false);
	// The keyed detail instance intentionally fences mutations to the version first presented to it.
	// svelte-ignore state_referenced_locally
	const initialVersion = incident?.version ?? 0;
	let viewVersion = $state(initialVersion);
	let ownerName = $derived(
		users.find((user: User) => user.id === incident?.ownerId)?.name ?? 'Unassigned'
	);

	async function claim() {
		if (!incident) return;
		const original = copyIncident(incident);
		onIncident({ ...original, ownerId: sessionUserId, status: 'investigating' }, 'optimistic');
		conflict = '';
		error = '';
		try {
			const { response, payload } = await claimIncident(original.id, sessionUserId, viewVersion);
			if (response.status === 409 && payload.error?.current) {
				onIncident(payload.error.current, 'authoritative');
				viewVersion = payload.error.current.version;
				conflict = 'This incident changed while you were viewing it. The latest owner is shown.';
			} else if (!response.ok)
				throw new Error(payload.error?.message ?? 'Unable to claim incident');
			else {
				onIncident(payload.incident, 'authoritative');
				viewVersion = payload.incident.version;
			}
		} catch (caught) {
			onIncident(original, 'optimistic');
			error = caught instanceof Error ? caught.message : 'Unable to claim incident';
		}
	}
	async function addComment(event: SubmitEvent) {
		event.preventDefault();
		if (!incident) return;
		const body = draft.trim();
		if (!body || [...body].length > 2000) {
			error = 'Comment must contain 1 to 2,000 characters.';
			return;
		}
		const original = copyIncident(incident);
		onIncident(
			{
				...original,
				comments: [
					...original.comments,
					{
						id: `pending-${crypto.randomUUID()}`,
						authorId: sessionUserId,
						body,
						createdAt: new Date().toISOString()
					}
				]
			},
			'optimistic'
		);
		draft = '';
		error = '';
		try {
			const { response, payload } = await submitComment(original.id, sessionUserId, body);
			if (!response.ok) throw new Error(payload.error?.message ?? 'Unable to add comment');
			onIncident(payload.incident, 'authoritative');
			viewVersion = payload.incident.version;
		} catch (caught) {
			onIncident(original, 'optimistic');
			draft = body;
			error = caught instanceof Error ? caught.message : 'Unable to add comment';
		}
	}
	async function analyze() {
		if (!incident) return;
		busy = true;
		error = '';
		try {
			const { response, payload } = await requestAnalysis(incident.id);
			if (!response.ok || !payload.job) throw new Error(payload.error?.message);
			job = payload.job;
		} catch (caught) {
			error = caught instanceof Error ? caught.message : 'Unable to start analysis';
		} finally {
			busy = false;
		}
	}
	onMount(() => {
		return subscribeLiveService({
			onJob: (next) => {
				if (next.id === job?.id) job = next;
			}
		});
	});
	function copyIncident(value: Incident): Incident {
		return { ...value, comments: value.comments.map((comment) => ({ ...comment })) };
	}
</script>

<section class="detail-panel" aria-label="Incident detail">
	{#if incident}
		<div class="detail-heading">
			<div>
				<span class="severity {incident.severity}">{incident.severity}</span>
				<h2>{incident.title}</h2>
			</div>
			<span class="version">Version {incident.version}</span>
		</div>
		<div class="facts">
			<div><span>Owner</span><strong>{ownerName}</strong></div>
			<div><span>Status</span><strong>{incident.status}</strong></div>
		</div>
		{#if conflict}<p class="alert" role="alert">{conflict}</p>{/if}{#if error}<p
				class="alert"
				role="alert"
			>
				{error}
			</p>{/if}<button class="primary" onclick={claim}>Claim incident</button>
		<section class="analysis-card">
			<div>
				<h3>Server analysis</h3>
				<p role="status">{job ? `Analysis ${job.status}` : 'Analysis has not started'}</p>
				{#if job?.result}<strong>{job.result.finding}</strong>{/if}
			</div>
			<button class="quiet" disabled={busy} onclick={analyze}>Start analysis</button>
		</section>
		<section class="comments">
			<h3>Response log</h3>
			{#if incident.comments.length === 0}<p class="empty">
					No comments yet.
				</p>{/if}{#each incident.comments as comment (comment.id)}<article>
					<strong>{users.find((user: User) => user.id === comment.authorId)?.name}</strong>
					<p>{comment.body}</p>
				</article>{/each}
			<form onsubmit={addComment}>
				<label>New comment<textarea bind:value={draft} maxlength="2000" required></textarea></label
				><button class="primary" type="submit">Add comment</button>
			</form>
		</section>
	{:else}<p class="empty">Select an incident to inspect its response history.</p>{/if}
</section>

// framework-comparison/participants/exact/src/IncidentDetail.tsx
import { peek, type Component } from '@exactjs/core';
import { SeverityBadge } from './IncidentQueue.jsx';
import { subscribeLiveService } from './live-service.js';
import { claimIncident, requestAnalysis, submitComment } from './service-client.js';
import type { AnalysisJob, Incident, User } from './types.js';

type DetailState = {
	draft: string;
	conflict: string;
	job: AnalysisJob | null;
	busy: boolean;
	error: string;
	viewedIncidentId: string;
	viewedVersion: number;
};

type DetailProps = {
	incident?: Incident;
	users: User[];
	sessionUserId: string;
	onIncident(incident: Incident, mode?: 'optimistic' | 'authoritative'): void;
};

/** Owns one durable detail surface, including optimistic work and its stale-view version fence. */
export function IncidentDetail(this: Component<DetailState>, props: DetailProps) {
	const state = this.state;
	this.state.draft = '';
	this.state.conflict = '';
	this.state.job = null;
	this.state.busy = false;
	this.state.error = '';
	this.state.viewedIncidentId = peek(() => props.incident?.id ?? '');
	this.state.viewedVersion = peek(() => props.incident?.version ?? 0);

	async function claim() {
		if (!props.incident || !props.sessionUserId) return;
		// A selection change starts a new view fence; live updates to the same selection deliberately do not.
		if (state.viewedIncidentId !== props.incident.id) {
			state.viewedIncidentId = props.incident.id;
			state.viewedVersion = props.incident.version;
		}
		const original = copyIncident(props.incident);
		props.onIncident(
			{ ...props.incident, ownerId: props.sessionUserId, status: 'investigating' },
			'optimistic'
		);
		state.conflict = '';
		state.error = '';
		try {
			const payload = await claimIncident(
				original.id,
				props.sessionUserId,
				state.viewedVersion,
				undefined
			);
			if (payload.status === 409 && payload.error?.current) {
				props.onIncident(payload.error.current, 'authoritative');
				state.viewedVersion = payload.error.current.version;
				state.conflict =
					'This incident changed while you were viewing it. The latest owner is shown.';
			} else if (payload.incident) {
				props.onIncident(payload.incident, 'authoritative');
				state.viewedVersion = payload.incident.version;
			} else props.onIncident(original, 'optimistic');
		} catch (caught) {
			props.onIncident(original, 'optimistic');
			state.error = caught instanceof Error ? caught.message : 'Unable to claim incident';
		}
	}

	async function addComment() {
		if (!props.incident) return;
		const body = state.draft.trim();
		if (!body || [...body].length > 2_000) {
			state.error = 'Comment must contain 1 to 2,000 characters.';
			return;
		}
		const original = copyIncident(props.incident);
		const temporary = {
			id: `pending-${crypto.randomUUID()}`,
			authorId: props.sessionUserId,
			body,
			createdAt: new Date().toISOString()
		};
		props.onIncident({ ...original, comments: [...original.comments, temporary] }, 'optimistic');
		state.draft = '';
		state.error = '';
		try {
			const payload = await submitComment(
				original.id,
				props.sessionUserId,
				body,
				crypto.randomUUID(),
				undefined
			);
			props.onIncident(payload.incident, 'authoritative');
			state.viewedVersion = payload.incident.version;
		} catch (caught) {
			props.onIncident(original, 'optimistic');
			state.draft = body;
			state.error = caught instanceof Error ? caught.message : 'Unable to add comment';
		}
	}

	async function startAnalysis() {
		if (!props.incident) return;
		state.busy = true;
		state.error = '';
		try {
			const payload = await requestAnalysis(props.incident.id);
			state.job = payload.job;
		} catch (caught) {
			state.error = caught instanceof Error ? caught.message : 'Unable to start analysis';
		} finally {
			state.busy = false;
		}
	}

	this.onMount(({ signal }) => {
		subscribeLiveService({ onJob: (job) => job.id === state.job?.id && (state.job = job) }, signal);
	});

	const ownerName =
		props.users.find((user) => user.id === props.incident?.ownerId)?.name ?? 'Unassigned';

	return () => (
		<section className="detail-panel" aria-label="Incident detail">
			{props.incident ? (
				<>
					<div className="detail-heading">
						<div>
							<SeverityBadge severity={props.incident.severity} />
							<h2>{props.incident.title}</h2>
						</div>
						<span className="version">Version {props.incident.version}</span>
					</div>
					<div className="facts">
						<div>
							<span>Owner</span>
							<strong>{ownerName}</strong>
						</div>
						<div>
							<span>Status</span>
							<strong>{props.incident.status}</strong>
						</div>
					</div>
					{this.state.conflict ? (
						<p className="alert" role="alert">
							{this.state.conflict}
						</p>
					) : null}
					{this.state.error ? (
						<p className="alert" role="alert">
							{this.state.error}
						</p>
					) : null}
					<button type="button" className="primary" onClick={claim}>
						Claim incident
					</button>
					<section className="analysis-card">
						<div>
							<h3>Server analysis</h3>
							<p role="status">
								{this.state.job ? `Analysis ${this.state.job.status}` : 'Analysis has not started'}
							</p>
							{this.state.job?.result ? <strong>{this.state.job.result.finding}</strong> : null}
						</div>
						<button
							type="button"
							className="quiet"
							disabled={this.state.busy}
							onClick={startAnalysis}
						>
							Start analysis
						</button>
					</section>
					<section className="comments">
						<h3>Response log</h3>
						{props.incident.comments.length === 0 ? (
							<p className="empty">No comments yet.</p>
						) : null}
						{props.incident.comments.map((comment) => (
							<article>
								<strong>{props.users.find((user) => user.id === comment.authorId)?.name}</strong>
								<p>{comment.body}</p>
							</article>
						))}
						<form
							onSubmit={(event) => {
								event.preventDefault();
								return addComment();
							}}
						>
							<label>
								New comment
								<textarea value:onInput={this.state.draft} maxLength={2000} required />
							</label>
							<button type="submit" className="primary">
								Add comment
							</button>
						</form>
					</section>
				</>
			) : (
				<p className="empty">Select an incident to inspect its response history.</p>
			)}
		</section>
	);
}

function copyIncident(incident: Incident): Incident {
	return { ...incident, comments: incident.comments.map((comment) => ({ ...comment })) };
}
